#version: '3'

services:
  app:
    build: .
    container_name: dotsafe-app
    restart: always
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html

#  postgres:
#    image: postgres:latest
#    container_name: dotsafe-db
#    restart: always
#    environment:
#     POSTGRES_USER: usr_dotsafe
#     POSTGRES_PASSWORD: neres0102
#     POSTGRES_DB: octadb
#    ports:
#      - "5432:5432"

#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@example.com
#      PGADMIN_DEFAULT_PASSWORD: teste21
#    ports:
#      - "8080:80"
